const imageList = [
  {
    id: 1,
    name: "prpv (1)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(1).jpg"),
  },
  {
    id: 2,
    name: "prpv (2)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(2).jpg"),
  },
  {
    id: 3,
    name: "prpv (3)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(3).jpg"),
  },
  {
    id: 4,
    name: "prpv (4)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(4).jpg"),
  },
  {
    id: 5,
    name: "prpv (5)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(5).jpg"),
  },
  {
    id: 6,
    name: "prpv (6)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(6).jpg"),
  },
  {
    id: 7,
    name: "prpv (7)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(7).jpg"),
  },
  {
    id: 8,
    name: "prpv (8)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(8).jpg"),
  },
  {
    id: 9,
    name: "prpv (9)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(9).jpg"),
  },
  {
    id: 10,
    name: "prpv (10)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(10).jpg"),
  },
  {
    id: 11,
    name: "prpv (11)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(11).jpg"),
  },
  {
    id: 12,
    name: "prpv (12)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(12).jpg"),
  },
  {
    id: 13,
    name: "prpv (13)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(13).jpg"),
  },
  {
    id: 14,
    name: "prpv (14)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(14).jpg"),
  },
  {
    id: 15,
    name: "prpv (15)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(15).jpg"),
  },
  {
    id: 16,
    name: "prpv (16)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(16).jpg"),
  },
  {
    id: 17,
    name: "prpv (17)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(17).jpg"),
  },
  {
    id: 18,
    name: "prpv (18)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(18).jpg"),
  },
  {
    id: 19,
    name: "prpv (19)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(19).jpg"),
  },
  {
    id: 20,
    name: "prpv (20)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(20).jpg"),
  },
  {
    id: 21,
    name: "prpv (21)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(21).jpg"),
  },
  {
    id: 22,
    name: "prpv (22)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(22).jpg"),
  },
  {
    id: 23,
    name: "prpv (23)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(23).jpg"),
  },
  {
    id: 24,
    name: "prpv (24)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(24).jpg"),
  },
  {
    id: 25,
    name: "prpv (25)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(25).jpg"),
  },
  {
    id: 26,
    name: "prpv (26)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(26).jpg"),
  },
  {
    id: 27,
    name: "prpv (27)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(27).jpg"),
  },
  {
    id: 28,
    name: "prpv (28)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(28).jpg"),
  },
  {
    id: 29,
    name: "prpv (29)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(29).jpg"),
  },
  {
    id: 30,
    name: "prpv (30)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(30).jpg"),
  },
  {
    id: 31,
    name: "prpv (31)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(31).jpg"),
  },
  {
    id: 32,
    name: "prpv (32)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(32).jpg"),
  },
  {
    id: 33,
    name: "prpv (33)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(33).jpg"),
  },
  {
    id: 34,
    name: "prpv (34)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(34).jpg"),
  },
  {
    id: 35,
    name: "prpv (35)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(35).jpg"),
  },
  {
    id: 36,
    name: "prpv (36)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(36).jpg"),
  },
  {
    id: 37,
    name: "prpv (37)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(37).jpg"),
  },
  {
    id: 38,
    name: "prpv (38)",
    tagline: "Starting at $69,420",
    image: require("../../../assets/images/prpv(38).jpg"),
  },
];

export default imageList;
